/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instantmessagingapp;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author Vidumini
 */
public class ChatPanel extends javax.swing.JPanel {

    /**
     * Creates new form ChatPanel
     */
    public ChatPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtTo = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtChat = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtSend = new javax.swing.JTextArea();
        btnSend = new javax.swing.JButton();
        lblBackChat = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(350, 400));
        setMinimumSize(new java.awt.Dimension(350, 400));
        setPreferredSize(new java.awt.Dimension(350, 400));

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setMaximumSize(new java.awt.Dimension(350, 400));
        jPanel1.setMinimumSize(new java.awt.Dimension(350, 400));
        jPanel1.setName(""); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(350, 400));
        jPanel1.setLayout(null);

        jLabel1.setText("To");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 14, 12, 14);
        jPanel1.add(txtTo);
        txtTo.setBounds(32, 11, 226, 20);

        txtChat.setEditable(false);
        txtChat.setColumns(20);
        txtChat.setFont(new java.awt.Font("Monospaced", 1, 13)); // NOI18N
        txtChat.setLineWrap(true);
        txtChat.setRows(5);
        txtChat.setAutoscrolls(false);
        txtChat.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtChat.setEnabled(false);
        jScrollPane1.setViewportView(txtChat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(32, 37, 226, 220);

        txtSend.setColumns(1);
        txtSend.setLineWrap(true);
        txtSend.setRows(5);
        txtSend.setAutoscrolls(false);
        jScrollPane2.setViewportView(txtSend);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(32, 258, 226, 30);

        btnSend.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instantmessagingapp/btnSend.png"))); // NOI18N
        btnSend.setBorderPainted(false);
        btnSend.setContentAreaFilled(false);
        btnSend.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSendMouseEntered(evt);
            }
        });
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });
        jPanel1.add(btnSend);
        btnSend.setBounds(148, 264, 120, 80);

        lblBackChat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instantmessagingapp/backChat.jpg"))); // NOI18N
        lblBackChat.setText("jLabel2");
        jPanel1.add(lblBackChat);
        lblBackChat.setBounds(0, 0, 350, 400);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSendActionPerformed

    private void btnSendMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSendMouseEntered
        btnSend.setRolloverIcon(new ImageIcon(getClass().getResource("/instantmessagingapp/btnSendClicked.png")));

    }//GEN-LAST:event_btnSendMouseEntered

    public JButton getSendButton(){
        return btnSend;
    }
    
    public JTextField getTextTo(){
        return txtTo;
    }
    
    public JTextArea getTextChat(){
        return txtChat;
    }
    
    public JTextArea getTextMsg(){
        return txtSend;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSend;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblBackChat;
    private javax.swing.JTextArea txtChat;
    private javax.swing.JTextArea txtSend;
    private javax.swing.JTextField txtTo;
    // End of variables declaration//GEN-END:variables
}
