package instantmessagingapp;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vidumini
 */
public class LoadingPanel extends javax.swing.JPanel {

    /**
     * Creates new form loadingPanel
     */
    public LoadingPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(280, 240));
        setMinimumSize(new java.awt.Dimension(280, 240));
        setPreferredSize(new java.awt.Dimension(280, 240));
        setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instantmessagingapp/2013-06-splash.gif"))); // NOI18N
        add(jLabel1);
        jLabel1.setBounds(0, 0, 280, 240);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
