/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package instantmessagingapp;

import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JTextField;

/**
 *
 * @author 123
 */
public class StartChat extends javax.swing.JPanel {

    /**
     * Creates new form StartChat
     */
    public StartChat() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtWith = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtWithMsg = new javax.swing.JTextField();
        btnWithStart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setMaximumSize(new java.awt.Dimension(350, 400));
        setMinimumSize(new java.awt.Dimension(350, 400));
        setPreferredSize(new java.awt.Dimension(350, 400));
        setLayout(null);

        jLabel1.setText("With");
        add(jLabel1);
        jLabel1.setBounds(82, 95, 50, 14);
        add(txtWith);
        txtWith.setBounds(166, 92, 138, 20);

        jLabel2.setText("Message");
        add(jLabel2);
        jLabel2.setBounds(82, 159, 60, 14);
        add(txtWithMsg);
        txtWithMsg.setBounds(166, 135, 138, 38);

        btnWithStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instantmessagingapp/btnStart.png"))); // NOI18N
        btnWithStart.setBorderPainted(false);
        btnWithStart.setContentAreaFilled(false);
        btnWithStart.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnWithStartMouseEntered(evt);
            }
        });
        btnWithStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWithStartActionPerformed(evt);
            }
        });
        add(btnWithStart);
        btnWithStart.setBounds(190, 190, 130, 50);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/instantmessagingapp/backStartChat.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        jLabel3.setMaximumSize(new java.awt.Dimension(350, 400));
        jLabel3.setMinimumSize(new java.awt.Dimension(350, 400));
        jLabel3.setPreferredSize(new java.awt.Dimension(350, 400));
        add(jLabel3);
        jLabel3.setBounds(0, 0, 350, 400);
    }// </editor-fold>//GEN-END:initComponents
    public JTextField getTextWith(){
        return txtWith;
    }
    
    public JTextField getTextWithMsg(){
        return txtWithMsg;
    }
    
    public JButton getBtnWithStart(){
        return btnWithStart;
    }
    
    private void btnWithStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWithStartActionPerformed
        
    }//GEN-LAST:event_btnWithStartActionPerformed

    private void btnWithStartMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnWithStartMouseEntered
        btnWithStart.setRolloverIcon(new ImageIcon(getClass().getResource("/instantmessagingapp/btnStartClicked.png")));
 
    }//GEN-LAST:event_btnWithStartMouseEntered


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnWithStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtWith;
    private javax.swing.JTextField txtWithMsg;
    // End of variables declaration//GEN-END:variables
}
